version: '3.7'
services:
    boozeapi:
        build: 
            context: BoozeApi
        ports:
            - "8080:80"
    dbmaintainer:
        depends_on: 
          - boozeapi
        build:
            context: dbmaintainer
    gui:
        depends_on: 
          - boozeapi
        build: 
            context: BoozeGui
        ports: 
            - "80:80"
