version: '3'
services:
    api:
        build: 
            context: .
            dockerfile: Dockerfile-api
        ports:
            - "80:80"
    dbmaintainer:
        depends_on: 
          - api
        build:
            context: .
            dockerfile: Dockerfile-dbmaintainer