version: '3.7'
services:
    boozeapi:
        build: 
            context: BoozeApi
        ports:
            - "80:80"
    dbmaintainer:
        depends_on: 
          - boozeapi
        build:
            context: dbmaintainer